### ISSUE TITLE
下载的数据是乱码，不知道你们是怎么处理的

### ISSUE THREAD

**Issue by jxlijunhao** [prozhuchen/2016CCF-sougou#1]
通过您提供的百度云盘提供的数据，下载后发现是乱码（ubuntu14.04系统），能提供一下原始最原始的文件么，比赛网站已经不能下载了～～

**Comment by prozhuchen** [comment]
是么。。。我们本机没有保留最原始的数据，也只是留了一份代码。。。要不然你问下其他参加该比赛的队伍有没有呢，对不起了。。



prozhuchen@gmail.com
 
发件人： jxlijunhao
发送时间： 2017-02-20 18:30
收件人： prozhuchen/2016CCF-sougou
抄送： Subscribed
主题： [prozhuchen/2016CCF-sougou] 下载的数据是乱码，不知道你们是怎么处理的 (#1)
通过您提供的百度云盘提供的数据，下载后发现是乱码（ubuntu14.04系统），能提供一下原始最原始的文件么，比赛网站已经不能下载了～～

**Comment by jxlijunhao** [comment]
@prozhuchen 我重新编码成utf-8就ok了

import os
import codecs
import pdb

data_train_path = 'user_tag_query.10W.TRAIN'
data_test_path = 'user_tag_query.10W.TEST'

fobj_train = open(data_train_path,'r')
fobj_test = open(data_test_path,'r')
fwobj_train = codecs.open('user_tag_query.10W.TRAIN_encode', 'w', 'utf-8')
fwobj_test = codecs.open('user_tag_query.10W.TEST_encode', 'w', 'utf-8')

count = 1
for line in fobj_train:
    print count
    count += 1
    line = line.strip().split('\t')
    line = [ w.decode('gbk','ignore') for w in line]
    s = '\t'.join(line)
    fwobj_train.write(s + '\n')
fwobj_train.close()

count = 1
for line in fobj_test:
    print count
    count += 1
    line = line.strip().split('\t')
    line = [ w.decode('gbk','ignore') for w in line]
    s = '\t'.join(line)
    fwobj_test.write(s + '\n')
fwobj_test.close()
